// <auto-generated />
using KonusarakOgrenWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KonusarakOgrenWebApp.Migrations.ExamDb
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20200914075642_ExamDbCreate")]
    partial class ExamDbCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("KonusarakOgrenWebApp.Models.ExamModel", b =>
                {
                    b.Property<int>("SınavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DogruCevapBir")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogruCevapDort")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogruCevapIki")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogruCevapUc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekBirA")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekBirB")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekBirC")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekBirD")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekDortA")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekDortB")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekDortC")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekDortD")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekIkiA")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekIkiB")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekIkiC")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekIkiD")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekUcA")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekUcB")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekUcC")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekUcD")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruAciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruBaslik")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruBir")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruDort")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruIki")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruUc")
                        .HasColumnType("TEXT");

                    b.HasKey("SınavId");

                    b.ToTable("ExamModels");
                });
#pragma warning restore 612, 618
        }
    }
}
